<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="115037" started-at="2017-01-31T06:39:33Z" finished-at="2017-01-31T06:41:28Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="115037" started-at="2017-01-31T06:39:33Z" finished-at="2017-01-31T06:41:28Z">
      <class name="com.mindtree.test.Application">
        <test-method status="PASS" signature="newRegisteration()[pri:0, instance:com.mindtree.test.Application@2ffb0fc2]" name="newRegisteration" duration-ms="83937" started-at="2017-01-31T12:09:33Z" finished-at="2017-01-31T12:10:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- newRegisteration -->
        <test-method status="FAIL" signature="Login()[pri:1, instance:com.mindtree.test.Application@2ffb0fc2]" name="Login" duration-ms="30787" started-at="2017-01-31T12:10:57Z" finished-at="2017-01-31T12:11:28Z">
          <exception class="junit.framework.AssertionFailedError">
            <message>
              <![CDATA[Login Failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError: Login Failed
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.assertTrue(Assert.java:22)
	at junit.framework.Assert.assertFalse(Assert.java:39)
	at com.mindtree.test.Application.Login(Application.java:93)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login -->
      </class> <!-- com.mindtree.test.Application -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
